server:
  port: 10011

#  Spring基本配置
spring:
  application:
    name: orchid-order

# Eureka实例配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://xxxxxx:8763/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.cloud.client.ip-address}.${spring.application.name}.${server.port}


## Feign客户端调用配置
feign:
#  开启熔断功能
  hystrix:
    enabled: true

  client:
    config:
      default:
#        修改Feign调用超时时间（默认是1秒就算超时）
        connectTimeout: 2000
        readTimeout: 2000



#hystrix熔断降级配置
hystrix:
  command:
#     Hystrix全局配置
    default:
#      强制开启断路器
#      circuitBreaker:
#        forceOpen: false
      execution:
        isolation:
#          隔离策略：THREAD(线程)和SEMAPHORE(信号量)
#          strategy: SEMAPHORE
          thread:
#             Hystrix全局超时配置（只有隔离模式是线程模式时才有效）
            timeoutInMilliseconds: 3000

